#!/bin/sh
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  Copyright (c) 2024: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  This does several checks that the env is suitable for iSH
#

notification() {
    if $use_wall; then
        wall --nobanner "$1"
    else
        echo "$1"
    fi
}
coreutils_check() {
    #
    #  On Alpine >= 3.20  iSH fails to handle /dev if coreutils is installed
    #  This gives a warning
    #

    # Only relevant for Alpine
    [ -f /etc/alpine-release ] || return

    # if version check is not available, no check can be done
    [ -f /opt/AOK/tools/vers_check.sh ] || return

    . /opt/AOK/tools/vers_check.sh

    # if older Alpine - all is good
    ! min_version 3.20 && return

    # If coreutils is not installed - all is good
    [ -f /usr/bin/coreutils ] || return

    #region coreutils warning
    notification "

WARNING: iSH will fail to hanlde /dev resources if coreutils is installed

"
    #endregion
}

#===============================================================
#
#   Main
#
#===============================================================

#
# If called from somewhere that isnt connected to stdio, make announcements
# using wall
#
if [ "$1" = "wall" ]; then
    use_wall=true
    shift
else
    use_wall=false
fi

coreutils_check
