#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034

skip_linters+=(
    markdownlint
)

# Explicit excludes, give entire filepath as listed by olint
excludes+=(
    CHANGES.md
    Docs/hostname.md
)

# Filter by prefix, as listed by olint
excluded_basename_prefixes+=(
    common_AOK/obs-sbin
)

override_linter_cmd["codespell"]="codespell -L aNULL,nulll,BU"
