#!/bin/sh
# this is sourced, shebang just to hint editors since no extension
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Copyright (c) 2023: Jacob.Lundqvist@gmail.com
#
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

# Let's set the path here since that covers both zsh and bash

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

if false; then
    #
    #  Set initial prompt
    #
    if [ -n "$ZSH_VERSION" ]; then
	# use nicer PS1 for zsh
	PS1='%m:%~%# '
    else
 	PS1='\h:\w\$ '
    fi
fi

if [ -f "/etc/opt/AOK/show_profile_hints" ]; then
    # shellcheck source=/dev/null
    . /etc/profile-hints
fi

/usr/local/bin/check-env-compatible

for script in /etc/profile.d/*.sh ; do
    if [ -r "$script" ] ; then
	# shellcheck source=/dev/null
        . "$script"
    fi
done
unset script

_user_profile="$HOME"/.profile
# shellcheck source=/dev/null
[ -f "$_user_profile" ] && . "$_user_profile"
unset _user_profile

echo
