#!/bin/sh
#
# Copyright (c) 2021-2024: Jacob.Lundqvist@gmail.com
# License: MIT
#
# Part of https://github.com/jaclu/helpful-scripts
#
#  Updates apt status of a Debian based box
#

err_msg() {
    msg="$1"
    exit_code="${2:-1}"

    [ -n "$msg" ] || {
        printf '\n\nERROR: err_msg() - no param\n' >&2
        exit 99
    }
    printf '\n\nERROR: %s\n' "$msg" >&2
    exit "$exit_code"
}

lbl_1() {
    [ -n "$1" ] || err_msg "lbl_1() no param"
    printf '\n===  %s  ===\n\n' "$1"
}

lbl_2() {
    [ -n "$1" ] || err_msg "lbl_2() no param"
    printf -- '---  %s\n' "$1"
}

lbl_3() {
    [ -n "$1" ] || err_msg "lbl_3() no param"
    printf -- ' --  %s\n' "$1"
}

display_time_elapsed() {
    dte_duration=$(($(date +%s) - t_start))

    if [ "$dte_duration" -gt 59 ]; then
        dte_hours=$((dte_duration / 3600))
        dte_minutes=$(((dte_duration % 3600) / 60))
        dte_seconds=$((dte_duration - dte_hours * 3600 - dte_minutes * 60))
        dte_elapsed=$(printf '%02d:%02d:%02d' "$dte_hours" "$dte_minutes" "$dte_seconds")
    else
        dte_elapsed=$(printf '%ss' "$dte_duration")
    fi
    echo
    printf 'Time elapsed: %s - %s\n' "$dte_elapsed" "$prog_name"
    echo
}

apt_task() {
    [ -n "$1" ] || err_msg "apt_task() - no params"
    lbl_3 "apt-get $*"
    apt-get "$@" || err_msg "Failed task: apt-get $*"
}

#===============================================================
#
#   Main
#
#===============================================================

prog_name=$(basename "$0")

# but ofcourse you do sysadmin as a regular user in Termux
if [ "$(uname -o)" != "Android" ] && [ "$(whoami)" != "root" ]; then
    echo "Executing $prog_name as root"

    sudo "$0" "$@"
    #  terminate the user initiated instance of the script
    exit "$?"
fi

t_start="$(date +%s)"

lbl_1 "Mapt - apt maintenance"

command -v apt >/dev/null || err_msg "apt not found - should NOT happen"
apt_task --fix-broken install
apt_task update
apt_task check
apt_task autoremove -y --purge
apt_task autoclean
apt_task -y full-upgrade
apt_task check

#
#  Check if reboot is required
#

if [ -f /var/run/reboot-required ]; then
    echo
    cat /var/run/reboot-required
    exit 1
fi

#
#  Any pending purges?
#
purge_candidates="$(dpkg -l | grep '^rc' | awk '{print $2}')"
if [ -n "$purge_candidates" ]; then
    echo
    lbl_2 "In need of purging"
    echo "$purge_candidates"
    exit 1
else
    lbl_2 "No  purges needed"
fi

[ "$1" != "no_timing" ] && display_time_elapsed
return 0
