#!/bin/sh
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Copyright (c) 2023-2024: Jacob.Lundqvist@gmail.com
#
#  Terminates the system, as nicely as possible,
#  to minimize risk of getting a crash popup
#

do_shutdown() {
    pids="$(echo "$key_pids" | tr '\n' ' ')"
    msg="Will shutdown, by killing based on: $1 - pids: $pids"
    echo
    echo "$msg"
    echo
    /usr/local/bin/logger "$prog_name" "$msg"

    #
    #  sync & sleep probably not needed on iSH, but its supposed to be
    #  done now :)
    #
    sync
    sync
    sleep 1

    echo "$pids" | xargs -r kill
    sleep 15
    /usr/local/bin/logger "$prog_name" "ERROR: Still alive after kills"
    exit
}

#===============================================================
#
#   Main
#
#===============================================================

prog_name=$(basename "$0")

[ "$(whoami)" != "root" ] && {
    echo "$prog_name must be run by root!"
    exit 1
}

#
#  Halting the system, different methods in falling priorities
#

# kill aok_launcher
key_pids="$(pgrep -f aok_launcher)"
[ -n "$key_pids" ] && do_shutdown aok_launcher

# a session on console
key_pids="$(pgrep -t pts/0)"
[ -n "$key_pids" ] && do_shutdown pts/0

# login sessions
key_pids="$(pgrep -f "login -f")"
[ -n "$key_pids" ] && do_shutdown "'login -f'"

# find init pid
key_pids="$(pgrep -f "init ")"
[ -n "$key_pids" ] && do_shutdown "init via pgrep"

# assume init is pid 1
key_pids="1"
do_shutdown "pid 1"
