#!/bin/sh
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  Copyright (c) 2023-2024: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Intended to be used for inittab tasks, in order to skip tasks if
#  recovery mode is selected
#

f_recovery_mode=/etc/opt/AOK/recovery-mode
f_recovery_log_file=/var/log/recovery-mode.log
s_prefix="$(date +"%Y-%m-%d %H:%M:%S")" 
[ -f "$f_recovery_mode" ] && {
    msg="$s_prefix in recovery mode - skipped ${*}"
    echo "$msg" >/dev/pts/0
    echo "$msg" >>"$f_recovery_log_file"
    exit 0
}

msg="$s_prefix R-check will run: ${*}"
echo "$msg" >>"$f_recovery_log_file"
echo "$msg" >/dev/pts/0

# run the intended task
"${@}"
ex_code="$?"
[ "$ex_code" -ne 0 ] && {
    # calculate new time stamp, since process might have taken some time
    msg "$(date +"%Y-%m-%d %H:%M:%S") - inittab failed - exit code: $ex_code"
    echo "$msg" >>"$f_recovery_log_file"
    echo "$msg" >/dev/pts/0
}
