#!/bin/sh
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  Copyright (c) 2023-2024: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Intended to be used for inittab tasks, in order to skip tasks if
#  recovery mode is selected
#

f_recovery_mode=/etc/opt/AOK/recovery-mode
f_recovery_log_file=/var/log/recovery-mode.log
[ -f "$f_recovery_mode" ] && {
    msg="$(date +"%Y-%m-%d %H:%M:%S") in recovery mode - skipped ${*}"
    echo "$msg" >/dev/stderr
    echo "$msg" >>"$f_recovery_log_file"
    exit 0
}

msg="$(date +"%Y-%m-%d %H:%M:%S") R-check will run: ${*}"
echo "$msg" >>"$f_recovery_log_file"
echo "$msg" >/dev/stderr

# run the intended task
"${@}"
