#!/bin/sh
#
# Copyright (c) 2021-2024: Jacob.Lundqvist@gmail.com
# License: MIT
#
# Part of https://github.com/jaclu/helpful_scripts
#
#  Updates apk status of an Alpine based box
#

display_time_elapsed() {
    _dte_label="$1"

    _dte_t_in="$(($(date +%s) - t_start))"
    _dte_mins="$((_dte_t_in / 60))"
    _dte_seconds="$((_dte_t_in - _dte_mins * 60))"

    #  Add zero prefix when < 10
    [ "$_dte_mins" -gt 0 ] && [ "$_dte_mins" -lt 10 ] && _dte_mins="0$_dte_mins"
    [ "$_dte_seconds" -lt 10 ] && _dte_seconds="0$_dte_seconds"

    echo
    echo "Time elapsed: $_dte_mins:$_dte_seconds - $_dte_label"
    echo
    unset _dte_t_in
    unset _dte_label
    unset _dte_mins
    unset _dte_seconds
}

#===============================================================
#
#   Main
#
#===============================================================

prog_name=$(basename "$0")
if [ "$(whoami)" != "root" ]; then
    echo "Executing $prog_name as root"

    #  Providing some env variables that are needed to be kept in the sudo
    sudo "$0" "$@"
    exit_code="$?"

    #  terminate the user initiated instance of the script
    exit "$exit_code"
fi

t_start="$(date +%s)"

echo "===  Mapk - apk maintenance  ==="

if ! apk fix || ! apk upgrade; then
    echo "ERROR detected by Mapk"
    exit 1
fi

#
#  Check if reboot is required
#
# /usr/lib/update-notifier/update-motd-reboot-required

display_time_elapsed "Mapk"
