#!/bin/sh
#
# Copyright (c) 2021-2024: Jacob.Lundqvist@gmail.com
# License: MIT
#
# Part of https://github.com/jaclu/helpful-scripts
#
#  Updates apk status of an Alpine based box
#

err_msg() {
    msg="$1"
    exit_code="${2:-1}"

    [ -n "$msg" ] || {
        printf '\n\nERROR: err_msg() - no param\n' >&2
        exit 99
    }
    printf '\n\nERROR: %s\n' "$msg" >&2
    exit "$exit_code"
}

lbl_1() {
    [ -n "$1" ] || err_msg "lbl_1() no param"
    printf '\n===  %s  ===\n\n' "$1"
}

lbl_2() {
    [ -n "$1" ] || err_msg "lbl_2() no param"
    printf -- '---  %s\n' "$1"
}

lbl_3() {
    [ -n "$1" ] || err_msg "lbl_3() no param"
    printf -- ' --  %s\n' "$1"
}

display_time_elapsed() {
    dte_duration=$(($(date +%s) - t_start))

    if [ "$dte_duration" -gt 59 ]; then
        dte_hours=$((dte_duration / 3600))
        dte_minutes=$(((dte_duration % 3600) / 60))
        dte_seconds=$((dte_duration - dte_hours * 3600 - dte_minutes * 60))
        dte_elapsed=$(printf '%02d:%02d:%02d' "$dte_hours" "$dte_minutes" "$dte_seconds")
    else
        dte_elapsed=$(printf '%ss' "$dte_duration")
    fi
    echo
    printf 'Time elapsed: %s - %s\n' "$dte_elapsed" "$prog_name"
    echo
}

apk_task() {
    [ -n "$1" ] || err_msg "apk_task() - no params"
    lbl_3 "apk $*"
    apk "$@" || err_msg "Failed task: apk $*"
}

#===============================================================
#
#   Main
#
#===============================================================

prog_name=$(basename "$0")

if [ "$(whoami)" != "root" ]; then
    echo "Executing $prog_name as root"

    #  Providing some env variables that are needed to be kept in the sudo
    sudo "$0" "$@"
    exit_code="$?"

    #  terminate the user initiated instance of the script
    exit "$exit_code"
fi

t_start="$(date +%s)"

lbl_1 "Mapk - apk maintenance"
apk_task update
apk_task upgrade
apk_task fix
# apk_task audit

#
#  Check if reboot is required
#
# /usr/lib/update-notifier/update-motd-reboot-required

[ "$1" != "no_timing" ] && display_time_elapsed
return 0
