#!/bin/sh
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Copyright (c) 2024: Jacob.Lundqvist@gmail.com
#
#  Save current aok_fs into saved_fs, tar file name will be
#  auto generated based on current FS
#

hide_run_as_root=1 . /opt/AOK/tools/run_as_root.sh
[ -z "$d_aok_etc" ] && . /opt/AOK/tools/utils.sh

. /opt/AOK/tools/aok_fs-common || {
    error_msg "Failed to source common-aok-fs-tar"
}

#
#  Select name for tarfile
#
f_alpine_release="$d_build_root"/etc/alpine-release
f_debian_version="$d_build_root"/etc/debian_version
if [ -f "$f_alpine_release" ]; then
    # seems to be Alpine
    tar_name="Alpine-$(cat "$f_alpine_release")"
elif [ -f "$f_debian_version" ]; then
    tar_name="Debian-$(cat "$f_debian_version")"
elif [ -f "$f_gentoo_version" ]; then
    tar_name="Gentoo-$(cut -d' ' -f 5 <"$f_gentoo_version")"
else
    error_msg "failed to detect Alpine/Debian"
fi
aok_vers="$(cat "$d_build_root"/etc/aok-fs-release)" || {
    error_msg "failed to detect aok-fs release"
}
tar_name="$d_aok_completed/$tar_name-AOK-$aok_vers-done.tgz"

#
#  Move aok fs to tmp save location
#
[ -d "$d_aok_fs_save" ] && {
    msg_2 "Removing existing directory and its contents: $d_aok_fs_save"
    rm -rf "$d_aok_fs_save" || error_msg "Failed to clear $d_aok_fs_save"
}
ensure_not_chrooted "$d_build_root"
mv "$d_build_root" "$d_aok_fs_save" || {
    error_msg "Failed to move $d_build_root -> $d_aok_fs_save"
}
cd "$d_aok_fs_save" || {
    error_msg "Failed to cd into $d_aok_fs_save"
}
# Extra check to ensure the location is correct
[ "$(pwd)" != "$d_aok_fs_save" ] && {
    error_msg "pwd is not $d_aok_fs_save"
}

#
#  Creating saved tgz
#
msg_1 "Will create: $(basename "$tar_name")"
msg_2 "Creating $f_tar_tmp_save"
cmd_pigz="$(command -v pigz)"
if [ -n "$cmd_pigz" ]; then
    msg_3 "Using $cmd_pigz"
    # time tar -cf - . | pigz -p 2 > foo.tgz
    tar -cf - . | $cmd_pigz >"$f_tar_tmp_save" || {
        echo
        error_msg "failed to tar"
    }
else
    msg_3 "No pigz"
    tar cfz "$f_tar_tmp_save" . || {
        echo
        error_msg "failed to tar"
    }
fi

#
# Storing it under its proper name in aok_completed
#
msg_3 "Renaming into: $(basename "$tar_name")"
mv "$f_tar_tmp_save" "$tar_name" || {
    error_msg "Failed to rename: $f_tar_tmp_save"
}
echo
echo "Saved as:"
echo "$tar_name"
echo

#
#  Moving fs back to aok_fs
#
[ -d "$d_build_root" ] && {
    msg_1 "Something else is using: $d_build_root"
    rm -rf "$d_aok_fs_save" || error_msg "Failed to clear $d_aok_fs_save"
    exit 1
}
mv "$d_aok_fs_save" "$d_build_root" || {
    error_msg "Failed to move $d_aok_fs_save -> $d_build_root"
}
